########## Testcase 0: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at RansomNote.check(Solution.java:15)
	at Solution.main(Solution.java:41)
----------------------------------------
########## Testcase 1: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at RansomNote.check(Solution.java:15)
	at Solution.main(Solution.java:41)
----------------------------------------
########## Testcase 2: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at RansomNote.check(Solution.java:15)
	at Solution.main(Solution.java:41)
----------------------------------------
########## Testcase 3: Failed ##########
Expected Output: 
No
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at RansomNote.check(Solution.java:15)
	at Solution.main(Solution.java:41)
----------------------------------------
########## Testcase 4: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at RansomNote.check(Solution.java:15)
	at Solution.main(Solution.java:41)
----------------------------------------
########## Testcase 5: Failed ##########
Expected Output: 
Yes
Your Output: 
Exception in thread "main" java.lang.NullPointerException
	at RansomNote.check(Solution.java:15)
	at Solution.main(Solution.java:41)
----------------------------------------
